spring.application.name=record-shop
thymeleaf.version=3.0.4.RELEASE
thymeleaf-layout-dialect.version=2.1.1
springdoc.swagger-ui.path=/api/v1/records/
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Default profile for local development
spring.profiles.active=local